create table if not exists request_case (
    id uuid primary key,
    request_type varchar(120) not null,
    workflow_state varchar(120) not null,
    created_by varchar(120) not null,
    assigned_to varchar(120),
    request_data text not null,
    created_at timestamp not null,
    updated_at timestamp not null
);

create table if not exists definition_module (
    id bigint generated by default as identity primary key,
    request_type varchar(120) not null,
    module_type varchar(80) not null,
    version integer not null,
    active boolean not null,
    definition_json text not null,
    created_at timestamp not null
);

create unique index if not exists ux_definition_module_version
    on definition_module(request_type, module_type, version);

create table if not exists calculation_result (
    id bigint generated by default as identity primary key,
    request_case_id uuid not null,
    calculation_id varchar(120) not null,
    result_json text not null,
    input_hash varchar(120) not null,
    calculated_by varchar(120) not null,
    calculated_at timestamp not null
);

create table if not exists audit_event (
    id bigint generated by default as identity primary key,
    request_case_id uuid,
    event_type varchar(120) not null,
    actor_id varchar(120) not null,
    from_workflow_state varchar(120),
    to_workflow_state varchar(120),
    definition_versions text,
    details_json text,
    created_at timestamp not null
);

create table if not exists demo_actor (
    id varchar(120) primary key,
    display_name varchar(200) not null,
    role varchar(120) not null,
    entitlements text not null,
    groups_json text not null
);

