import type { UiConfigNode } from '../uiDefinition';

export const companyProfilePage = {
	id: 'companyProfile',
	label: 'Company Profile',
	type: 'page',
	visibleRule: null,
	enabledRule: null,
	required: false,
	requiredRule: null,
	children: [
		{
			id: 'companyName',
			type: 'field',
			component: 'textInput',
			dataPath: 'company.name',
			label: 'Company Name',
			visibleRule: null,
			enabledRule: 'canEditInvestmentReview',
			required: true,
			requiredRule: null,
		},
		{
			id: 'companyStage',
			type: 'field',
			component: 'radioGroup',
			dataPath: 'company.stage',
			label: 'Company Stage',
			visibleRule: null,
			enabledRule: 'canEditInvestmentReview',
			required: true,
			requiredRule: null,
		},
		{
			id: 'companySector',
			type: 'field',
			component: 'dropdown',
			dataPath: 'company.sector',
			label: 'Industry Sector',
			visibleRule: null,
			enabledRule: 'canEditInvestmentReview',
			required: true,
			requiredRule: null,
		},
		{
			id: 'companyFoundedDate',
			type: 'field',
			component: 'dateInput',
			dataPath: 'company.foundedDate',
			label: 'Date Founded',
			helperText: 'Choose today or an earlier date.',
			constraints: { maxDate: 'today' },
			visibleRule: null,
			enabledRule: 'canEditInvestmentReview',
			required: true,
			requiredRule: null,
		},
		{
			id: 'companyIncorporated',
			type: 'field',
			component: 'radioGroup',
			dataPath: 'company.incorporated',
			label: 'Is the company legally incorporated?',
			visibleRule: null,
			enabledRule: 'canEditInvestmentReview',
			required: true,
			requiredRule: null,
		},
		{
			id: 'companyProfileRiskConfirmationSection',
			type: 'section',
			label: 'Risk Officer Confirmation',
			visibleRule: 'showRiskOfficerConfirmations',
			enabledRule: 'canEditRiskReview',
			required: false,
			requiredRule: null,
			children: [
				{
					id: 'companyProfileRiskConfirmation',
					type: 'field',
					component: 'radioGroup',
					dataPath: 'risk.pageConfirmations.companyProfile',
					label: 'Company profile review decision',
					visibleRule: null,
					enabledRule: null,
					required: false,
					requiredRule: 'showRiskOfficerConfirmations',
				},
				{
					id: 'companyProfileRiskNote',
					type: 'field',
					component: 'textarea',
					dataPath: 'risk.pageConfirmationNotes.companyProfile',
					label: 'Reason for referring the company profile back',
					visibleRule: 'showCompanyProfileRiskNote',
					enabledRule: null,
					required: false,
					requiredRule: 'showCompanyProfileRiskNote',
				},
			],
		},
	],
} satisfies UiConfigNode;
