import type { UiConfigNode } from "../uiDefinition";

export const riskExceptionsPage = {
  id: "riskExceptions",
  label: "Risk & Exceptions",
  type: "page",
  visibleRule: null,
  enabledRule: null,
  required: false,
  requiredRule: null,
  children: [
    {
      id: "analystExceptions",
      type: "collection",
      component: "exceptionList",
      dataPath: "exceptions",
      label: "Analyst Exceptions",
      visibleRule: null,
      enabledRule: null,
      required: false,
      requiredRule: null,
      requiredFields: ["description", "severity"],
      filter: { path: "$item.createdBy.role", op: "eq", value: "InvestmentAnalyst" },
      actions: [{ id: "addAnalystException", type: "action", actionType: "collection.addItem", visibleRule: null, enabledRule: "canEditInvestmentReview", required: false, requiredRule: null }],
    },
    {
      id: "riskExceptions",
      type: "collection",
      component: "exceptionList",
      dataPath: "exceptions",
      label: "Risk Exceptions",
      visibleRule: "showRiskExceptions",
      enabledRule: null,
      required: false,
      requiredRule: null,
      requiredFields: ["description", "severity"],
      filter: { path: "$item.createdBy.role", op: "eq", value: "RiskOfficer" },
      actions: [{ id: "addRiskException", type: "action", actionType: "collection.addItem", visibleRule: null, enabledRule: "canEditRiskReview", required: false, requiredRule: null }],
    },
  ],
} satisfies UiConfigNode;
