spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/approval_platform_poc
    username: poc
    password: poc
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: true
  flyway:
    enabled: true

